theme: minima

title: "PhotoDemon: the fast, free, portable photo editor"
baseurl: "/photodemon-dot-org"
url: "https://photodemon.org"
# to serve the site locally without the baseurl entry screwing things up, use "jekyll server --baseurl ''"
rss: true
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-redirect-from
